name: test

on:
  push:

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Tree
        run: |
          tree external

      - name: Update submodule
        run: |
          git submodule update --remote

      - name: Tree
        run: |
          tree external
